# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agent-pool-demo
  namespace: edu
spec:
  organization: veloso
  token:
    secretKeyRef:
      name: tfc-owner
      key: token
  name: agent-pool-demo
  agentTokens:
    - name: agent-pool-demo-token
  agentDeployment:
    replicas: 1
    spec:
      containers:
        - name: tfc-agent
          image: rvsacrtestrvs.azurecr.io/tfc-agent-custom:latest
      terminationGracePeriodSeconds: 900
  # autoscaling:
  #   minReplicas: 1
  #   maxReplicas: 2
    # cooldownPeriod:
    #   scaleUpSeconds: 30
    #   scaleDownSeconds: 30