---
- name: "Configurar UMA notification (simples) - pre-plan"
  hosts: localhost
  gather_facts: false

  vars:
    api_base: "https://app.terraform.io/api/v2"

    # Ambiente
    hcp_org: "{{ lookup('env','HCP_ORG') }}"
    hcp_token: "{{ lookup('env','HCP_TF_TOKEN') }}"
    ws_name: "{{ lookup('env','TFC_WORKSPACE_NAME') }}"

    notify_name: "{{ lookup('env','NOTIFY_NAME') | default('Generic webhook', true) }}"
    notify_destination_type: "{{ lookup('env','NOTIFY_DESTINATION_TYPE') | default('generic', true) }}"
    notify_url: "{{ lookup('env','NOTIFY_URL') | default('', true) }}"
    notify_triggers_raw: "{{ lookup('env','NOTIFY_TRIGGERS') | default('run:created,run:completed,run:errored', true) }}"
    notify_enabled_str: "{{ lookup('env','WORKSPACE_NOTIFICATION_ENABLED') | default('true', true) }}"

  tasks:
    - name: "Normalizar enabled e triggers"
      set_fact:
        notify_enabled: "{{ (notify_enabled_str | lower) in ['1','true','yes','on'] }}"
        notify_triggers: "{{ notify_triggers_raw.split(',') | map('trim') | list }}"

    - name: "Checar URL quando o destino exige URL (generic/slack/teams)"
      assert:
        that:
          - notify_destination_type in ['email'] or (notify_url | length) > 0
        fail_msg: "NOTIFY_URL é obrigatório para destination-type {{ notify_destination_type }}"

    - name: "Obter workspace (org + nome)"
      uri:
        url: "{{ api_base }}/organizations/{{ hcp_org }}/workspaces/{{ ws_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: ws_resp

    - name: "Extrair workspace_id"
      set_fact:
        workspace_id: "{{ ws_resp.json.data.id }}"

    # Tentativa 1: endpoint aninhado (type SINGULAR)
    - name: "Criar notification (POST nested)"
      uri:
        url: "{{ api_base }}/workspaces/{{ workspace_id }}/notification-configurations"
        method: POST
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
          Accept: "application/vnd.api+json"
        body_format: json
        body:
          data:
            type: "notification-configuration"    # SINGULAR
            attributes:
              name: "{{ notify_name }}"
              destination-type: "{{ notify_destination_type }}"
              url: "{{ notify_url if notify_destination_type != 'email' else omit }}"
              triggers: "{{ notify_triggers }}"
              enabled: "{{ (notify_enabled | bool) | to_json | from_json }}"
        return_content: true
        status_code: [200, 201, 400, 409, 422, 500]
      register: create_nested
      failed_when: false

    # Fallback: endpoint global (type PLURAL + relationships.workspace)
    - name: "Criar notification (POST global) - fallback quando 500 no nested"
      uri:
        url: "{{ api_base }}/notification-configurations"
        method: POST
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
          Accept: "application/vnd.api+json"
        body_format: json
        body:
          data:
            type: "notification-configurations"   # PLURAL no endpoint global
            attributes:
              name: "{{ notify_name }}"
              destination-type: "{{ notify_destination_type }}"
              url: "{{ notify_url if notify_destination_type != 'email' else omit }}"
              triggers: "{{ notify_triggers }}"
              enabled: "{{ (notify_enabled | bool) | to_json | from_json }}"
            relationships:
              workspace:
                data:
                  type: "workspaces"
                  id: "{{ workspace_id }}"
        return_content: true
        status_code: [200, 201, 400, 409, 422, 500]
      register: create_global
      failed_when: false
      when: (create_nested.status | default(0)) == 500

    - name: "Resumo"
      debug:
        msg:
          - "workspace_id={{ workspace_id }}"
          - "name={{ notify_name }}"
          - "destination-type={{ notify_destination_type }}"
          - "enabled_requested={{ notify_enabled }}"
          - "triggers={{ notify_triggers }}"
          - "nested_status={{ create_nested.status | default('n/a') }}"
          - "nested_x_request_id={{ create_nested.x_request_id | default('n/a') }}"
          - "global_status={{ create_global.status | default('skipped') }}"
          - "global_x_request_id={{ create_global.x_request_id | default('n/a') }}"
          - "errors_nested={{ create_nested.json.errors | default([]) }}"
          - "errors_global={{ create_global.json.errors | default([]) }}"
