---
- name: "Configurar notification no HCP Terraform (pre-plan)"
  hosts: localhost
  gather_facts: false

  vars:
    api_base: "https://app.terraform.io/api/v2"

    # Environment (Variable Set / pre-plan.sh)
    hcp_org: "{{ lookup('env', 'HCP_ORG') }}"
    hcp_token: "{{ lookup('env', 'HCP_TF_TOKEN') }}"
    ws_name: "{{ lookup('env', 'TFC_WORKSPACE_NAME') }}"

    # Só cria quando esta flag estiver true (aceita WORKSPACE_NOTIFICATION_ENABLED ou workspace_notification_enabled)
    workspace_notification_enabled: "{{ (lookup('env','WORKSPACE_NOTIFICATION_ENABLED') or lookup('env','workspace_notification_enabled') or 'false') | bool }}"

    # Parâmetros da notification (sempre generic)
    notify_name: "{{ lookup('env', 'NOTIFY_NAME') | default('Generic webhook', true) }}"
    notify_url: "{{ lookup('env', 'NOTIFY_URL') | default('', true) }}"
    notify_triggers_raw: "{{ lookup('env', 'NOTIFY_TRIGGERS') | default('run:created,run:completed,run:errored', true) }}"

  tasks:
    - name: "Encerrar cedo se a flag não estiver habilitada"
      meta: end_play
      when: not workspace_notification_enabled

    - name: "Montar lista de triggers"
      set_fact:
        notify_triggers: "{{ notify_triggers_raw.split(',') | map('trim') | list }}"

    - name: "Checar URL (obrigatória para generic)"
      assert:
        that:
          - (notify_url | length) > 0
        fail_msg: "NOTIFY_URL é obrigatório para destination-type generic"

    - name: "Obter workspace (org + nome)"
      uri:
        url: "{{ api_base }}/organizations/{{ hcp_org }}/workspaces/{{ ws_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: ws_resp

    - name: "Extrair workspace_id"
      set_fact:
        workspace_id: "{{ ws_resp.json.data.id }}"

    - name: "Listar notification-configurations do workspace"
      uri:
        url: "{{ api_base }}/workspaces/{{ workspace_id }}/notification-configurations"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: list_resp

    # → Checa EXISTÊNCIA por NOME (independente do tipo)
    - name: "Filtrar por nome exato"
      set_fact:
        existing_nc: >-
          {{
            (list_resp.json.data | default([]))
            | selectattr('attributes.name', 'equalto', notify_name)
            | list
          }}

    - name: "Marcar se já existe"
      set_fact:
        already_exists: "{{ (existing_nc | length) > 0 }}"
        notification_id: "{{ (existing_nc[0].id) if (existing_nc | length) > 0 else '' }}"

    # --- CREATE: apenas quando NÃO existir ---
    - name: "Criar notification generic (enabled=true) se NÃO existir"
      uri:
        url: "{{ api_base }}/workspaces/{{ workspace_id }}/notification-configurations"
        method: POST
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
          Accept: "application/vnd.api+json"
        body_format: json
        body:
          data:
            type: "notification-configurations"   # PLURAL no create
            attributes:
              name: "{{ notify_name }}"
              enabled: true                       # cria já habilitada
              destination-type: "generic"
              url: "{{ notify_url }}"
              triggers: "{{ notify_triggers }}"
        return_content: true
        status_code: [201, 400]                   # 400 = verify falhou; ok pro seu teste
      register: create_resp
      failed_when: false
      when: not already_exists

    - name: "Definir notification_id quando acabou de criar (se tiver)"
      set_fact:
        notification_id: "{{ create_resp.json.data.id | default(notification_id | default('')) }}"
      when: not already_exists

    - name: "Resumo"
      debug:
        msg:
          - "workspace_id={{ workspace_id }}"
          - "notification_name={{ notify_name }}"
          - "already_exists={{ already_exists }}"
          - "notification_id={{ notification_id | default('unknown') }}"
          - "created_now={{ (not already_exists) }}"
          - "post_status={{ create_resp.status | default('skipped') }}"
          - "obs=se post_status=400, o create falhou por verify; como seu objetivo é só testar a criação, o play não falha"
