---
- name: "Configurar notification no HCP Terraform (pre-plan)"
  hosts: localhost
  gather_facts: false

  vars:
    api_base: "https://app.terraform.io/api/v2"

    # Environment (Variable Set / pre-plan.sh)
    hcp_org: "{{ lookup('env', 'HCP_ORG') }}"
    hcp_token: "{{ lookup('env', 'HCP_TF_TOKEN') }}"
    ws_name: "{{ lookup('env', 'TFC_WORKSPACE_NAME') }}"

    notify_name: "{{ lookup('env', 'NOTIFY_NAME') | default('Webhook server test', true) }}"
    notify_destination_type: "{{ lookup('env', 'NOTIFY_DESTINATION_TYPE') | default('generic', true) }}"
    notify_url: "{{ lookup('env', 'NOTIFY_URL') | default('', true) }}"
    notify_triggers_raw: "{{ lookup('env', 'NOTIFY_TRIGGERS') | default('run:created,run:completed,run:errored', true) }}"

  tasks:
    - name: "Montar lista de triggers"
      set_fact:
        notify_triggers: "{{ notify_triggers_raw.split(',') | map('trim') | list }}"

    - name: "Checar URL quando o destino não é email"
      assert:
        that:
          - notify_destination_type == 'email' or (notify_url | length) > 0
        fail_msg: "NOTIFY_URL é obrigatório para destination-type {{ notify_destination_type }}"

    - name: "Obter workspace (org + nome)"
      uri:
        url: "{{ api_base }}/organizations/{{ hcp_org }}/workspaces/{{ ws_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: ws_resp

    - name: "Extrair workspace_id"
      set_fact:
        workspace_id: "{{ ws_resp.json.data.id }}"

    - name: "Listar notification-configurations do workspace"
      uri:
        url: "{{ api_base }}/workspaces/{{ workspace_id }}/notification-configurations"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: list_resp

    - name: "Filtrar por nome + destination-type"
      set_fact:
        existing_nc: >-
          {{
            (list_resp.json.data | default([]))
            | selectattr('attributes.name', 'equalto', notify_name)
            | selectattr('attributes.destination-type', 'equalto', notify_destination_type)
            | list
          }}

    # --- CREATE APENAS (enabled=false p/ evitar verify automático no POST) ---
    - name: "Criar notification se não existir"
      uri:
        url: "{{ api_base }}/workspaces/{{ workspace_id }}/notification-configurations"
        method: POST
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Content-Type: "application/vnd.api+json"
          Accept: "application/vnd.api+json"
        body_format: json
        body:
          data:
            type: "notification-configurations"     # PLURAL no create
            attributes:
              name: "{{ notify_name }}"
              enabled: false                        # cria desabilitada para garantir sucesso
              destination-type: "{{ notify_destination_type }}"
              url: "{{ notify_url if notify_destination_type != 'email' else omit }}"
              triggers: "{{ notify_triggers }}"
        return_content: true
        status_code: [201]
      register: create_resp
      when: (existing_nc | length) == 0

    - name: "Definir notification_id (novo ou existente)"
      set_fact:
        notification_id: "{{ (create_resp.json.data.id if (existing_nc | length) == 0 else existing_nc[0].id) }}"

    - name: "Resumo"
      debug:
        msg:
          - "workspace_id={{ workspace_id }}"
          - "notification_id={{ notification_id }}"
          - "name={{ notify_name }}"
          - "destination-type={{ notify_destination_type }}"
          - "created={{ (existing_nc | length) == 0 }}"
