---
- name: "Associar policy set cujo nome corresponde ao m칩dulo derivado do nome da workspace"
  hosts: localhost
  gather_facts: false

  vars:
    api_base: "https://app.terraform.io/api/v2"

    # Vari치veis de ambiente padr칚o do hook
    hcp_org: "{{ lookup('env','HCP_ORG') }}"
    hcp_token: "{{ lookup('env','HCP_TF_TOKEN') }}"
    ws_name_raw: "{{ lookup('env','TFC_WORKSPACE_NAME') }}"

  tasks:
    - name: "Validar vari치veis obrigat칩rias"
      assert:
        that:
          - hcp_org|length > 0
          - hcp_token|length > 0
          - ws_name_raw|length > 0
        fail_msg: "Faltam vari치veis HCP_ORG / HCP_TF_TOKEN / TFC_WORKSPACE_NAME"

    - name: "Normalizar nome da workspace"
      set_fact:
        ws_name: "{{ ws_name_raw | trim }}"

    - name: "Obter workspace (org + nome)"
      uri:
        url: "{{ api_base }}/organizations/{{ hcp_org }}/workspaces/{{ ws_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Accept: "application/vnd.api+json"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: ws_resp

    - name: "workspace_id"
      set_fact:
        workspace_id: "{{ ws_resp.json.data.id }}"

    - name: "Montar lista de partes do workspace (ws_parts)"
      set_fact:
        ws_parts: "{{ ws_name.split('-') }}"

    - name: "Determinar module_name a partir das partes da workspace"
      set_fact:
        module_name: "{{ ws_parts[2] if (ws_parts | length) >= 3 else ws_name }}"

    # 游댢 FIX: separar em dois tasks
    - name: "Codificar module_name"
      set_fact:
        module_name_enc: "{{ module_name | urlencode }}"

    - name: "Montar URL de busca com search[name]=module_name_enc"
      set_fact:
        policy_search_url: >-
          https://app.terraform.io/api/v2/organizations/{{ hcp_org }}/policy-sets?search%5Bname%5D={{ module_name_enc }}

    - name: "Buscar policy sets pelo module_name derivado"
      uri:
        url: "{{ policy_search_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Accept: "application/vnd.api+json"
          Content-Type: "application/vnd.api+json"
        return_content: true
        status_code: [200]
      register: psets_resp
      failed_when: false

    - name: "Extrair candidates se resposta for 200"
      set_fact:
        candidates: >-
          {{
            (psets_resp.status == 200)
            | ternary(psets_resp.json.data | default([]), [])
          }}

    - name: "Resumo da busca"
      debug:
        msg:
          - "workspace={{ ws_name }}"
          - "module_name(search[name])={{ module_name }}"
          - "status_busca={{ psets_resp.status | default('n/a') }}"
          - "policy_sets_encontrados={{ candidates | length }}"
          - "nomes={{ candidates | map(attribute='attributes.name') | list }}"

    - name: "Encerrar play se nenhuma policy encontrada"
      meta: end_play
      when: (candidates | length) == 0

    # Idempotente: se j치 estiver associado, o endpoint retorna 409
    - name: "Associar policy sets encontrados ao workspace"
      uri:
        url: "{{ api_base }}/policy-sets/{{ item.id }}/relationships/workspaces"
        method: POST
        headers:
          Authorization: "Bearer {{ hcp_token }}"
          Accept: "application/vnd.api+json"
          Content-Type: "application/vnd.api+json"
        body_format: json
        body:
          data:
            - { id: "{{ workspace_id }}", type: "workspaces" }
        return_content: true
        status_code: [200, 201, 204, 409, 422]
      register: attach_resp
      failed_when: false
      loop: "{{ candidates }}"
      loop_control:
        label: "{{ item.attributes.name }}"

    - name: "Resumo final"
      debug:
        msg:
          - "workspace={{ ws_name }} ({{ workspace_id }})"
          - "policy_sets_processados={{ candidates | map(attribute='attributes.name') | list }}"
          - "status_por_policy={{ attach_resp.results | map(attribute='status') | list }}"
          - "errors={{ attach_resp.results | map(attribute='json.errors') | list }}"
