name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/ 

permissions:
  contents: read
  id-token: write

env:
  REGISTRY_NAME: rvsacrtestrvs
  IMAGE_NAME: tfc-agent-custom

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: client-secret

      - name: Azure ACR login
        run: az acr login --name $REGISTRY_NAME

      - name: Get short SHA
        id: vars
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build -f docker/Dockerfile -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ steps.vars.outputs.tag }} .
          docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:${{ steps.vars.outputs.tag }}
